-- ============================================================
-- BG_MIGRATE_DATA.sql
-- Migrate data from old AXON-style tables → new clean tables
-- Schema : SC_QAWS
-- Run as : SC_QAWS or DBA
-- Pre-req: BG_NEW_STRUCTURE.sql must be run first
-- ============================================================
-- OLD TABLES USED (read-only, not dropped here):
--   SC_QAWS.GLOSSARY              — main hierarchy (EAV/self-ref)
--   SC_QAWS.CUSTOM_FIELD          — EAV metadata (AR names, defs, etc.)
--   SC_QAWS.SECURITY_CLASSIFICATION — old security lookup
--   SC_QAWS.STATUS                — old status lookup
--
-- OLD type → NEW node_type_id mapping:
--   parent_id IS NULL → 1  GLOSSARY (root)
--   type = 1          → 2  TOPIC
--   type IN (2, 5)    → 3  THEME
--   type = 9          → 4  DATASET
--   type = 3 (others) → 5  TERM
--
-- OLD custom_field metadata IDs:
--   120 = AR name         → name_ar
--   121 = AR definition   → definition_ar
--   146 = source          → source
--   149 = justification   → justification
--   150 = use category    → use_category_id (mapped to BG_USE_CATEGORY)
-- ============================================================


-- ============================================================
-- STEP 1 — Migrate BG_SECURITY_CLASS from SECURITY_CLASSIFICATION
--          Preserves old IDs so security_class_id FK still maps correctly
-- ============================================================
INSERT INTO SC_QAWS.BG_SECURITY_CLASS (id, name_en, name_ar)
SELECT
    sc.id,
    sc.primaryname,
    CAST(SUBSTR(cf.customfieldvalue, 1, 200) AS VARCHAR2(200))  AS name_ar
FROM SC_QAWS.SECURITY_CLASSIFICATION sc
LEFT JOIN SC_QAWS.CUSTOM_FIELD cf
       ON cf.facetobjectid         = sc.id
      AND cf.customfieldmetadataid = 120;

COMMIT;

-- Fix identity sequence after explicit ID inserts
DECLARE
    l_max NUMBER;
BEGIN
    SELECT NVL(MAX(id), 0) + 1 INTO l_max FROM SC_QAWS.BG_SECURITY_CLASS;
    EXECUTE IMMEDIATE
        'ALTER TABLE SC_QAWS.BG_SECURITY_CLASS MODIFY id '
     || 'GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH ' || l_max || ')';
END;
/


-- ============================================================
-- STEP 2 — Migrate BG_GLOSSARY_NODE from GLOSSARY + CUSTOM_FIELD
--
--   We keep the same ID values as the old GLOSSARY table so that
--   parent_id relationships resolve automatically without any
--   intermediate mapping table.
--
--   BG_USE_CATEGORY ID mapping (from old text value in CF 150):
--     'Data Collection'                  → 1
--     'Data Analysis and Dissemination'  → 2
--     'Policy and Regulation'            → 3
--     'Other'                            → 4
--     anything else / NULL               → NULL
-- ============================================================
INSERT INTO SC_QAWS.BG_GLOSSARY_NODE (
    id,
    parent_id,
    node_type_id,
    name_en,
    name_ar,
    definition_en,
    definition_ar,
    ref_number,
    code,
    source,
    justification,
    use_category_id,
    status_id,
    security_class_id,
    is_public,
    created_by,
    created_date,
    updated_by,
    updated_date
)
SELECT
    /* ── Identity ──────────────────────────────────── */
    g.id,
    g.parent_id,

    /* ── Node type mapping ──────────────────────────── */
    CASE
        WHEN g.parent_id  IS NULL   THEN 1   -- GLOSSARY (root container)
        WHEN g."type"     = 1       THEN 2   -- TOPIC
        WHEN g."type"     IN (2, 5) THEN 3   -- THEME
        WHEN g."type"     = 9       THEN 4   -- DATASET
        ELSE                             5   -- TERM (type=3, 4, 10, etc.)
    END                                      AS node_type_id,

    /* ── Bilingual names ────────────────────────────── */
    g.primaryname                            AS name_en,
    CAST(SUBSTR(cf_ar.customfieldvalue,  1, 1000) AS VARCHAR2(1000))  AS name_ar,

    /* ── Bilingual definitions ──────────────────────── */
    CAST(SUBSTR(g.description,           1, 4000) AS VARCHAR2(4000))  AS definition_en,
    CAST(SUBSTR(cf_def.customfieldvalue, 1, 4000) AS VARCHAR2(4000))  AS definition_ar,

    /* ── Reference & Code ───────────────────────────── */
    g.refnumber                              AS ref_number,
    -- code: numeric code for TERM nodes only (old system = ID value)
    CASE WHEN g."type" NOT IN (1, 2, 5, 9) AND g.parent_id IS NOT NULL
         THEN g.id
         ELSE NULL
    END                                      AS code,

    /* ── Term metadata ──────────────────────────────── */
    CAST(SUBSTR(cf_src.customfieldvalue, 1, 4000) AS VARCHAR2(4000))  AS source,
    CAST(SUBSTR(cf_jus.customfieldvalue, 1, 4000) AS VARCHAR2(4000))  AS justification,

    -- Map old text use value → BG_USE_CATEGORY id
    CASE TRIM(cf_use.customfieldvalue)
        WHEN 'Data Collection'                   THEN 1
        WHEN 'Data Analysis and Dissemination'   THEN 2
        WHEN 'Policy and Regulation'             THEN 3
        WHEN 'Other'                             THEN 4
        ELSE NULL
    END                                          AS use_category_id,

    /* ── Status (old 1=Active→1, old 3=Pending→3, else→2 Draft) ── */
    CASE g.status
        WHEN 1 THEN 1
        WHEN 3 THEN 3
        ELSE        2
    END                                          AS status_id,

    /* ── Security classification (default 1 if NULL) ─ */
    NVL(g.securityclassification, 1)             AS security_class_id,

    /* ── Visibility ─────────────────────────────────── */
    NVL(g.ispublic, 0)                           AS is_public,

    /* ── Audit ──────────────────────────────────────── */
    NULL                                         AS created_by,
    NVL(g.createdatetime,      SYSDATE)          AS created_date,
    NULL                                         AS updated_by,
    NVL(g.lastupdatedatetime,  SYSDATE)          AS updated_date

FROM SC_QAWS.GLOSSARY g

/* AR name (custom_field 120) */
LEFT JOIN SC_QAWS.CUSTOM_FIELD cf_ar
       ON cf_ar.facetobjectid         = g.id
      AND cf_ar.customfieldmetadataid = 120

/* AR definition (custom_field 121) */
LEFT JOIN SC_QAWS.CUSTOM_FIELD cf_def
       ON cf_def.facetobjectid         = g.id
      AND cf_def.customfieldmetadataid = 121

/* Source (custom_field 146) */
LEFT JOIN SC_QAWS.CUSTOM_FIELD cf_src
       ON cf_src.facetobjectid         = g.id
      AND cf_src.customfieldmetadataid = 146

/* Justification (custom_field 149) */
LEFT JOIN SC_QAWS.CUSTOM_FIELD cf_jus
       ON cf_jus.facetobjectid         = g.id
      AND cf_jus.customfieldmetadataid = 149

/* Use category text (custom_field 150) */
LEFT JOIN SC_QAWS.CUSTOM_FIELD cf_use
       ON cf_use.facetobjectid         = g.id
      AND cf_use.customfieldmetadataid = 150;

COMMIT;


-- ============================================================
-- STEP 3 — Fix identity sequence on BG_GLOSSARY_NODE
--           After bulk insert with explicit IDs, reset the
--           IDENTITY sequence to MAX(id)+1 so new inserts
--           from APEX don't collide with migrated IDs.
-- ============================================================
DECLARE
    l_max NUMBER;
BEGIN
    SELECT NVL(MAX(id), 0) + 1 INTO l_max FROM SC_QAWS.BG_GLOSSARY_NODE;
    EXECUTE IMMEDIATE
        'ALTER TABLE SC_QAWS.BG_GLOSSARY_NODE MODIFY id '
     || 'GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH ' || l_max || ')';
    DBMS_OUTPUT.PUT_LINE('BG_GLOSSARY_NODE identity reset to: ' || l_max);
END;
/


-- ============================================================
-- STEP 4 — Verification queries
--           Run these to confirm migration counts
-- ============================================================

-- Row counts per node type
SELECT
    nt.code                 AS node_type,
    nt.name_en              AS type_label,
    COUNT(n.id)             AS migrated_rows
FROM SC_QAWS.BG_NODE_TYPE nt
LEFT JOIN SC_QAWS.BG_GLOSSARY_NODE n ON n.node_type_id = nt.id
GROUP BY nt.id, nt.code, nt.name_en
ORDER BY nt.id;

-- Compare old vs new total count
SELECT 'OLD glossary table'      AS source, COUNT(*) AS total FROM SC_QAWS.GLOSSARY       UNION ALL
SELECT 'NEW BG_GLOSSARY_NODE'    AS source, COUNT(*) AS total FROM SC_QAWS.BG_GLOSSARY_NODE;

-- Orphan check — parent_id must always resolve
SELECT COUNT(*) AS orphan_count
FROM SC_QAWS.BG_GLOSSARY_NODE n
WHERE n.parent_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM SC_QAWS.BG_GLOSSARY_NODE p WHERE p.id = n.parent_id
  );

-- Security class check — no NULLs allowed
SELECT COUNT(*) AS missing_sec_class
FROM SC_QAWS.BG_GLOSSARY_NODE
WHERE security_class_id IS NULL;

-- Use category mapping check — how many terms have a use category
SELECT
    uc.name_en          AS use_category,
    COUNT(n.id)         AS term_count
FROM SC_QAWS.BG_USE_CATEGORY uc
LEFT JOIN SC_QAWS.BG_GLOSSARY_NODE n
       ON n.use_category_id = uc.id
      AND n.node_type_id    = 5
GROUP BY uc.id, uc.name_en
ORDER BY uc.id;

-- Sample: first 10 TERM rows with all joins resolved
SELECT
    n.id,
    n.ref_number,
    n.code,
    n.name_en,
    n.name_ar,
    nt.name_en          AS node_type,
    st.name_en          AS status,
    sc.name_en          AS security_class,
    uc.name_en          AS use_category,
    p.name_en           AS parent_name
FROM SC_QAWS.BG_GLOSSARY_NODE n
JOIN SC_QAWS.BG_NODE_TYPE     nt ON nt.id = n.node_type_id
JOIN SC_QAWS.BG_STATUS        st ON st.id = n.status_id
JOIN SC_QAWS.BG_SECURITY_CLASS sc ON sc.id = n.security_class_id
LEFT JOIN SC_QAWS.BG_USE_CATEGORY uc ON uc.id = n.use_category_id
LEFT JOIN SC_QAWS.BG_GLOSSARY_NODE p  ON p.id  = n.parent_id
WHERE n.node_type_id = 5   -- TERM nodes only
  AND ROWNUM <= 10
ORDER BY n.id;

-- ============================================================
-- DONE
-- ============================================================
-- Old tables (GLOSSARY, CUSTOM_FIELD, etc.) are NOT dropped.
-- They remain as backup until the new structure is validated.
-- Once confirmed, they can be archived or dropped separately.
-- ============================================================
