-- ============================================================
-- BG_NEW_STRUCTURE.sql
-- Business Glossary — Clean Oracle APEX Table Structure
-- Schema : SC_QAWS
-- Run as : SC_QAWS or DBA
-- ============================================================
-- TABLES CREATED (in order):
--   1. BG_NODE_TYPE        Lookup — GLOSSARY / TOPIC / THEME / DATASET / TERM
--   2. BG_STATUS           Lookup — ACTIVE / DRAFT / PENDING_REVIEW
--   3. BG_SECURITY_CLASS   Lookup — security levels
--   4. BG_USE_CATEGORY     Lookup — term use categories
--   5. BG_GLOSSARY_NODE    Main   — full hierarchy (parent-child via parent_id)
-- ============================================================


-- ============================================================
-- SAFETY: Drop existing new tables if re-running this script
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SC_QAWS.BG_GLOSSARY_NODE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SC_QAWS.BG_USE_CATEGORY  CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SC_QAWS.BG_SECURITY_CLASS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SC_QAWS.BG_STATUS        CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SC_QAWS.BG_NODE_TYPE     CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/


-- ============================================================
-- 1. BG_NODE_TYPE
--    Defines what each row in BG_GLOSSARY_NODE represents.
--    IDs are fixed — referenced in application logic.
-- ============================================================
CREATE TABLE SC_QAWS.BG_NODE_TYPE (
    id        NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    code      VARCHAR2(50)    NOT NULL,
    name_en   VARCHAR2(200)   NOT NULL,
    name_ar   VARCHAR2(200),
    sort_order NUMBER         DEFAULT 0,
    CONSTRAINT uq_bgnt_code UNIQUE (code)
);

COMMENT ON TABLE  SC_QAWS.BG_NODE_TYPE          IS 'Lookup — node types for BG_GLOSSARY_NODE hierarchy';
COMMENT ON COLUMN SC_QAWS.BG_NODE_TYPE.code     IS 'Short code used in application logic';
COMMENT ON COLUMN SC_QAWS.BG_NODE_TYPE.name_en  IS 'English label';
COMMENT ON COLUMN SC_QAWS.BG_NODE_TYPE.name_ar  IS 'Arabic label';

-- Seed data (IDs are fixed — do NOT change)
INSERT INTO SC_QAWS.BG_NODE_TYPE (id, code, name_en, name_ar, sort_order) VALUES (1, 'GLOSSARY', 'Glossary', 'قاموس',           1);
INSERT INTO SC_QAWS.BG_NODE_TYPE (id, code, name_en, name_ar, sort_order) VALUES (2, 'TOPIC',    'Topic',    'موضوع',           2);
INSERT INTO SC_QAWS.BG_NODE_TYPE (id, code, name_en, name_ar, sort_order) VALUES (3, 'THEME',    'Theme',    'محور',            3);
INSERT INTO SC_QAWS.BG_NODE_TYPE (id, code, name_en, name_ar, sort_order) VALUES (4, 'DATASET',  'Dataset',  'مجموعة بيانات',   4);
INSERT INTO SC_QAWS.BG_NODE_TYPE (id, code, name_en, name_ar, sort_order) VALUES (5, 'TERM',     'Term',     'مصطلح',           5);
COMMIT;


-- ============================================================
-- 2. BG_STATUS
--    Term / node lifecycle status.
--    IDs 1 and 3 kept same as old system for easy mapping.
-- ============================================================
CREATE TABLE SC_QAWS.BG_STATUS (
    id        NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    code      VARCHAR2(50)    NOT NULL,
    name_en   VARCHAR2(200)   NOT NULL,
    name_ar   VARCHAR2(200),
    CONSTRAINT uq_bgs_code UNIQUE (code)
);

COMMENT ON TABLE  SC_QAWS.BG_STATUS         IS 'Lookup — lifecycle status for glossary nodes';
COMMENT ON COLUMN SC_QAWS.BG_STATUS.code    IS 'Short code: ACTIVE / DRAFT / PENDING_REVIEW';

-- Seed data (1=Active, 2=Draft, 3=Pending Review — matches old status IDs)
INSERT INTO SC_QAWS.BG_STATUS (id, code, name_en, name_ar) VALUES (1, 'ACTIVE',          'Active',         'نشط');
INSERT INTO SC_QAWS.BG_STATUS (id, code, name_en, name_ar) VALUES (2, 'DRAFT',           'Draft',          'مسودة');
INSERT INTO SC_QAWS.BG_STATUS (id, code, name_en, name_ar) VALUES (3, 'PENDING_REVIEW',  'Pending Review', 'قيد المراجعة');
COMMIT;


-- ============================================================
-- 3. BG_SECURITY_CLASS
--    Security classification levels.
--    Populated by migration script from SECURITY_CLASSIFICATION.
-- ============================================================
CREATE TABLE SC_QAWS.BG_SECURITY_CLASS (
    id        NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name_en   VARCHAR2(200)   NOT NULL,
    name_ar   VARCHAR2(200)
);

COMMENT ON TABLE  SC_QAWS.BG_SECURITY_CLASS        IS 'Lookup — security classification levels';
COMMENT ON COLUMN SC_QAWS.BG_SECURITY_CLASS.name_en IS 'English label (e.g. Public, Internal)';
COMMENT ON COLUMN SC_QAWS.BG_SECURITY_CLASS.name_ar IS 'Arabic label';


-- ============================================================
-- 4. BG_USE_CATEGORY
--    Use category for terms (shown on workflow submission form).
-- ============================================================
CREATE TABLE SC_QAWS.BG_USE_CATEGORY (
    id        NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name_en   VARCHAR2(200)   NOT NULL,
    name_ar   VARCHAR2(200)
);

COMMENT ON TABLE  SC_QAWS.BG_USE_CATEGORY        IS 'Lookup — intended use category for glossary terms';
COMMENT ON COLUMN SC_QAWS.BG_USE_CATEGORY.name_en IS 'English label';
COMMENT ON COLUMN SC_QAWS.BG_USE_CATEGORY.name_ar IS 'Arabic label';

-- Seed data (IDs are fixed — referenced in migration script)
INSERT INTO SC_QAWS.BG_USE_CATEGORY (id, name_en, name_ar) VALUES (1, 'Data Collection',                   'جمع البيانات');
INSERT INTO SC_QAWS.BG_USE_CATEGORY (id, name_en, name_ar) VALUES (2, 'Data Analysis and Dissemination',   'تحليل البيانات ونشرها');
INSERT INTO SC_QAWS.BG_USE_CATEGORY (id, name_en, name_ar) VALUES (3, 'Policy and Regulation',             'السياسة والتنظيم');
INSERT INTO SC_QAWS.BG_USE_CATEGORY (id, name_en, name_ar) VALUES (4, 'Other',                             'أخرى');
COMMIT;


-- ============================================================
-- 5. BG_GLOSSARY_NODE  (MAIN TABLE)
--    Single self-referencing table for the full hierarchy:
--      GLOSSARY → TOPIC → THEME → [DATASET →] TERM
--
--    Rules:
--      parent_id = NULL           → root GLOSSARY node
--      node_type_id = 1 GLOSSARY  → parent_id must be NULL
--      node_type_id = 2 TOPIC     → parent must be GLOSSARY
--      node_type_id = 3 THEME     → parent must be TOPIC
--      node_type_id = 4 DATASET   → parent must be THEME
--      node_type_id = 5 TERM      → parent must be THEME or DATASET
--
--    Columns with * apply only to TERM nodes (NULL for others).
-- ============================================================
CREATE TABLE SC_QAWS.BG_GLOSSARY_NODE (

    -- ── Identity ─────────────────────────────────────────────
    id                  NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
    parent_id           NUMBER,                         -- FK → self (NULL for root)
    node_type_id        NUMBER          NOT NULL,       -- FK → BG_NODE_TYPE

    -- ── Bilingual names (all node types) ─────────────────────
    name_en             VARCHAR2(1000)  NOT NULL,
    name_ar             VARCHAR2(1000),

    -- ── Bilingual definitions (*TERM only) ───────────────────
    definition_en       VARCHAR2(4000),
    definition_ar       VARCHAR2(4000),

    -- ── Reference & Code (*TERM / all nodes have ref_number) ─
    ref_number          VARCHAR2(200),                  -- e.g. GLOS-123, DS-456
    code                NUMBER,                         -- *TERM: auto-incremented numeric code

    -- ── Term metadata (*TERM only) ───────────────────────────
    source              VARCHAR2(4000),
    justification       VARCHAR2(4000),
    use_category_id     NUMBER,                         -- FK → BG_USE_CATEGORY

    -- ── Status & Visibility (all node types) ─────────────────
    status_id           NUMBER          DEFAULT 1 NOT NULL,  -- FK → BG_STATUS
    security_class_id   NUMBER          DEFAULT 1 NOT NULL,  -- FK → BG_SECURITY_CLASS
    is_public           NUMBER(1)       DEFAULT 1 NOT NULL,  -- 1=visible, 0=hidden

    -- ── Audit ─────────────────────────────────────────────────
    created_by          VARCHAR2(200),
    created_date        DATE            DEFAULT SYSDATE NOT NULL,
    updated_by          VARCHAR2(200),
    updated_date        DATE            DEFAULT SYSDATE NOT NULL,

    -- ── Constraints ──────────────────────────────────────────
    CONSTRAINT pk_bgn            PRIMARY KEY (id),
    CONSTRAINT uq_bgn_ref        UNIQUE      (ref_number),
    CONSTRAINT chk_bgn_public    CHECK       (is_public IN (0, 1)),
    CONSTRAINT fk_bgn_parent     FOREIGN KEY (parent_id)        REFERENCES SC_QAWS.BG_GLOSSARY_NODE (id),
    CONSTRAINT fk_bgn_type       FOREIGN KEY (node_type_id)     REFERENCES SC_QAWS.BG_NODE_TYPE     (id),
    CONSTRAINT fk_bgn_status     FOREIGN KEY (status_id)        REFERENCES SC_QAWS.BG_STATUS        (id),
    CONSTRAINT fk_bgn_secclass   FOREIGN KEY (security_class_id)REFERENCES SC_QAWS.BG_SECURITY_CLASS(id),
    CONSTRAINT fk_bgn_use_cat    FOREIGN KEY (use_category_id)  REFERENCES SC_QAWS.BG_USE_CATEGORY  (id)
);

-- Comments
COMMENT ON TABLE  SC_QAWS.BG_GLOSSARY_NODE                   IS 'Business Glossary — unified hierarchy table (Glossary→Topic→Theme→Dataset→Term)';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.id                IS 'Primary key';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.parent_id         IS 'Self-referencing FK — NULL for root glossary nodes';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.node_type_id      IS 'FK → BG_NODE_TYPE: 1=GLOSSARY, 2=TOPIC, 3=THEME, 4=DATASET, 5=TERM';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.name_en           IS 'English name — required for all node types';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.name_ar           IS 'Arabic name';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.definition_en     IS 'English definition — TERM nodes only';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.definition_ar     IS 'Arabic definition — TERM nodes only';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.ref_number        IS 'Human-readable unique reference e.g. GLOS-123';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.code              IS 'Short numeric code — TERM nodes only, auto-incremented';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.source            IS 'Source / reference — TERM nodes only';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.justification     IS 'Submission justification — TERM nodes only (workflow)';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.use_category_id   IS 'FK → BG_USE_CATEGORY — TERM nodes only (workflow)';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.status_id         IS 'FK → BG_STATUS: 1=Active, 2=Draft, 3=Pending Review';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.security_class_id IS 'FK → BG_SECURITY_CLASS';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.is_public         IS '1 = visible in UI, 0 = hidden (draft/pending)';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.created_by        IS 'APEX username who created this row';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.created_date      IS 'Creation timestamp';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.updated_by        IS 'APEX username who last updated this row';
COMMENT ON COLUMN SC_QAWS.BG_GLOSSARY_NODE.updated_date      IS 'Last update timestamp';

-- ── Indexes ──────────────────────────────────────────────────
CREATE INDEX SC_QAWS.idx_bgn_parent_id    ON SC_QAWS.BG_GLOSSARY_NODE (parent_id);
CREATE INDEX SC_QAWS.idx_bgn_node_type    ON SC_QAWS.BG_GLOSSARY_NODE (node_type_id);
CREATE INDEX SC_QAWS.idx_bgn_status       ON SC_QAWS.BG_GLOSSARY_NODE (status_id);
CREATE INDEX SC_QAWS.idx_bgn_is_public    ON SC_QAWS.BG_GLOSSARY_NODE (is_public);
CREATE INDEX SC_QAWS.idx_bgn_parent_type  ON SC_QAWS.BG_GLOSSARY_NODE (parent_id, node_type_id);
CREATE INDEX SC_QAWS.idx_bgn_code         ON SC_QAWS.BG_GLOSSARY_NODE (code);
/


-- ============================================================
-- SUMMARY
-- ============================================================
-- Tables created:
--   SC_QAWS.BG_NODE_TYPE      (5 rows seeded)
--   SC_QAWS.BG_STATUS         (3 rows seeded)
--   SC_QAWS.BG_SECURITY_CLASS (populated by BG_MIGRATE_DATA.sql)
--   SC_QAWS.BG_USE_CATEGORY   (4 rows seeded)
--   SC_QAWS.BG_GLOSSARY_NODE  (populated by BG_MIGRATE_DATA.sql)
--
-- Run next: BG_MIGRATE_DATA.sql
-- ============================================================
